// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsJGYuku8zGE23jkyeLd4S2rsWBN8kWc4',
    appId: '1:227012792994:web:7a758832d4f8242f37bdfb',
    messagingSenderId: '227012792994',
    projectId: 'gglfuel',
    authDomain: 'gglfuel.firebaseapp.com',
    storageBucket: 'gglfuel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjucG493lG-LWeJM0_nvRPeNmfftXaOxk',
    appId: '1:227012792994:android:99a95dac87ec724937bdfb',
    messagingSenderId: '227012792994',
    projectId: 'gglfuel',
    storageBucket: 'gglfuel.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsJGYuku8zGE23jkyeLd4S2rsWBN8kWc4',
    appId: '1:227012792994:web:d7b856fd87cbb7df37bdfb',
    messagingSenderId: '227012792994',
    projectId: 'gglfuel',
    authDomain: 'gglfuel.firebaseapp.com',
    storageBucket: 'gglfuel.firebasestorage.app',
  );
}
